services:
  - type: web
    name: a2dev-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GITHUB_TOKEN
        value: YOUR_GITHUB_TOKEN_HERE
