name: Coverage Report

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
  - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Set up the desired Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Install dependencies and test requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest codecov pytest-cov

      # Run tests and generate a coverage report in XML format
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-branch --cov-report=xml

      # Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: 3A2DEV/3A2BOT
